version: '3.8'

networks:
    laravel:

services:
  php-apache:
    container_name: sc-test-web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/php-apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "2800:80"
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mariadb:latest
    container_name: sc-test-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=aA123456
      - MYSQL_DATABASE=sc_db
      - MYSQL_USER=sc_user
      - MYSQL_PASSWORD=sc_pwd
      - TZ=Europe/Budapest
    ports:
      - "2802:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      - laravel

  adminer:
    image: adminer
    container_name: sc-test-adminer
    ports:
      - "2801:8080"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: price
      ADMINER_PLUGINS: dump-date edit-calendar enum-option enum-types sql-log struct-comments tables-filter
    networks:
      - laravel
